CREATE DATABASE IF NOT EXISTS sims_db;
USE sims_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS spare_part (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  unitPrice DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  totalPrice DECIMAL(12,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS stock_in (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sparePartId INT NOT NULL,
  stockInQuantity INT NOT NULL,
  stockInDate DATE NOT NULL,
  FOREIGN KEY (sparePartId) REFERENCES spare_part(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_out (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sparePartId INT NOT NULL,
  userId INT NOT NULL,
  stockOutQuantity INT NOT NULL,
  stockOutUnitPrice DECIMAL(10,2) NOT NULL,
  stockOutTotalPrice DECIMAL(12,2) NOT NULL,
  stockOutDate DATE NOT NULL,
  FOREIGN KEY (sparePartId) REFERENCES spare_part(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
